### ISSUE TITLE
SparCC progress

### ISSUE THREAD

**Issue by Robvh-git** [JCSzamosi/SparCC3#2]
Dear @JCSzamosi,

thank you very much for making this SparCC3 port. I've got 2 questions relating to SparCC:

1) is SparCC3 now fully functioning and reliable? I saw some comments mentioning that only SparCC works, and not spearman & pearson correlations, but is that fixed?

2) I also tried to get the 'original' SparCC working, but kept receiving errors (also in conda env with Python 2.6-7 etc). Could you get the original package working? Or is that why you developed SparCC3?

Thanks!

**Comment by JCSzamosi** [comment]
Hi @Robvh-git thanks for your questions!

1. I have not done any development on SparCC since I made the port, so spearman and pearson still do not work. I'm not likely to get to that any time soon, but pull requests are welcome if you would like to implement them.
2. It's been a while, so I don't remember exactly, but I think I made this port because I could not get the original to work. 

I'm going to close this issue now, but feel free to re-open it if you need more info

Jake
